### PR TITLE
Fix compilation with OpenSSL 1.1

### LINKED ISSUE #21: Beam crashes after update to openssl 1.1
@waddlesplash could you look into it?

```
Debug information for team /boot/system/apps/Beam/Beam (1559):
CPU(s): 6x Intel Core™ i5-8400T
Memory: 15.39 GiB total, 697.20 MiB used
Haiku revision: hrev54105 Apr 28 2020 18:17:24 (x86_64)

Active Threads:
	thread 1559: Beam (main)
	thread 1564: helper 
	thread 1565: MailMonitorWorker 
	thread 1566: MailMonitor 
	thread 1567: StoredActionFlusher 
	thread 1569: w>Jobs 
	thread 1570: PeopleMonitor 
	thread 1579: w>Beam log: Errors 
	thread 1581: w>Beam 
	thread 1612: bubble 
	thread 1615: team 1559 debug task 
	thread 1614: IMAP_beos13@gmail.com 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7f69e93b7e50	0xf4d0ece530	ssl3_ctx_ctrl + 0x140 
			Disassembly:
[...]
			Frame memory:
				[0x7f69e93b7e30]  P~;.i....:......   50 7e 3b e9 69 7f 00 00 e0 3a de 01 0e 02 00 00
				[0x7f69e93b7e40]  .........;......   00 00 00 00 00 00 00 00 18 3b de 01 0e 02 00 00
		0x7f69e93b7ec0	0x20e01be1079	BmOpenSslNetEndpoint::ContextManager::ContextManager() + 0x109 
		0x7f69e93b7ee0	0x20e01bdf3e3	_GLOBAL(int16, , bool, , , , , , , , int64) + 0x13 
		0x7f69e93b7f90	0x15a504fc34b	_ZL17init_dependenciesP7image_tb.constprop.8 + 0x1bb 
		0x7f69e93b7ff0	0x15a504fcdd8	load_library + 0xc8 
		0x7f69e93b8010	0x15a50501051	export_load_add_on(char const*, unsigned int) + 0x11 
		0x7f69e93b8280	0x8ba231f7a9	BmNetEndpointRoster::_InitializeIfNeeded() + 0x2a9 
		0x7f69e93b82a0	0x8ba231fc3a	BmNetEndpointRoster::CreateEndpoint() + 0xa 
		0x7f69e93b8340	0x8ba2320d71	BmNetJobModel::Connect(BNetAddress const*) + 0x71 
		0x7f69e93b83c0	0x8ba231be4e	BmImap::StateConnect() + 0x5e 
		0x7f69e93b8430	0x8ba231a921	BmImap::StartJob() + 0x121 
		0x7f69e93b8480	0x1f5a438a6a7	BmJobModel::doStartJob() + 0x77 
		0x7f69e93b8500	0x1f5a438adc0	BmJobModel::ThreadStartFunc(void*) + 0x150 
		0x7f69e93b8520	0x1685924ef67	thread_entry + 0x17 
		00000000	0x7fb8ee16b260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000000f4d0ece530
			  rsp:	0x00007f69e93b7e30
			  rbp:	0x00007f69e93b7e50
			  rax:	0x000000f4d0ece530
			  rbx:	0x000002859da66b30
			  rcx:	0x000000f4d0efda80
			  rdx:	0x0000000000000001
			  rsi:	0x000000000000005e
			  rdi:	0x000002859da66b30
			   r8:	0x000002859da66b30
			   r9:	0x0000000000000001
			  r10:	0x0000000000000013
			  r11:	0x0000000000000001
			  r12:	0x0000000000000000
			  r13:	0x0000000000000000
			  r14:	0x00007f69e93b7f20
			  r15:	0x0000000000000000
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0xaf80, 0x816b, 0x156, 0, 0xaee0, 0x816b, 0x156, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	4930	0x49606d000	0x49607a000	0x49627a000	0x49627b000	add-on 	/boot/system/add-ons/Translators/ICNSTranslator
	4917	0x8351be000	0x8351cc000	0x8353cc000	0x8353cd000	add-on 	/boot/system/add-ons/Translators/TIFFTranslator
	4919	0x9ba6bf000	0x9ba6cf000	0x9ba8cf000	0x9ba8d0000	add-on 	/boot/system/add-ons/Translators/TGATranslator
	4946	0x122bf93000	0x122bfa4000	0x122c1a4000	0x122c1a5000	lib    	/boot/system/lib/libroot-addon-icu.so
	4942	0x12d873c000	0x12d8751000	0x12d8951000	0x12d8952000	lib    	/boot/system/lib/libImath-2_4.so.24.0.0
	4934	0x136fd56000	0x136fd6c000	0x136ff6b000	0x136ff6d000	add-on 	/boot/system/add-ons/Translators/GIFTranslator
	4905	0x23e6dd6000	0x23e7725000	0x23e7925000	0x23e795b000	lib    	/boot/system/lib/libmupdf.so.1.8
	4933	0x30df562000	0x30df56e000	0x30df76e000	0x30df76f000	add-on 	/boot/system/add-ons/Translators/HVIFTranslator
	4925	0x330148c000	0x330149b000	0x330169b000	0x330169c000	add-on 	/boot/system/add-ons/Translators/PNGTranslator
	4920	0x36d1c8c000	0x36d1c9c000	0x36d1e9b000	0x36d1e9c000	add-on 	/boot/system/add-ons/Translators/SGITranslator
	4894	0x3c9e440000	0x3c9e46e000	0x3c9e66e000	0x3c9e6a2000	lib    	/boot/system/lib/libicutu.so.57.2
	4877	0x3cccb3f000	0x3cccb83000	0x3cccd83000	0x3cccd84000	lib    	/boot/system/lib/libpcre.so.1.2.12
	4876	0x3e0eaac000	0x3e0eaae000	0x3e0ecad000	0x3e0ecae000	lib    	/boot/system/lib/libpcreposix.so.0.0.7
	4924	0x4acaeb2000	0x4acaebe000	0x4acb0be000	0x4acb0c0000	add-on 	/boot/system/add-ons/Translators/PPMTranslator
	4874	0x55b576a000	0x55b57c5000	0x55b59c5000	0x55b59cc000	lib    	/boot/system/apps/Beam/lib/bmGuiBase.so
	4921	0x6100509000	0x610051b000	0x610071a000	0x610071c000	add-on 	/boot/system/add-ons/Translators/RTFTranslator
	4906	0x611e8eb000	0x611e999000	0x611eb99000	0x611eba0000	lib    	/boot/system/lib/libfreetype.so.6.16.1
	4943	0x65b0d4d000	0x65b0d5b000	0x65b0f5b000	0x65b0f5c000	add-on 	/boot/system/add-ons/Translators/BMPTranslator
	4890	0x679f3c4000	0x679f640000	0x679f840000	0x679f855000	lib    	/boot/system/lib/libicui18n.so.57.2
	4935	0x6b7fa4d000	0x6b7fa5a000	0x6b7fc5a000	0x6b7fc5b000	add-on 	/boot/system/add-ons/Translators/EXRTranslator
	4913	0x6bd7f09000	0x6bd809c000	0x6bd829c000	0x6bd82aa000	lib    	/boot/system/lib/libdjvulibre.so.21.6.0
	4912	0x6d671bf000	0x6d671c8000	0x6d673c8000	0x6d673ca000	add-on 	/boot/system/add-ons/Translators/DjVuTranslator
	4895	0x77f41bf000	0x77f4353000	0x77f4553000	0x77f4568000	lib    	/boot/system/lib/libicuuc.so.57.2
	4914	0x881a8a9000	0x881a8bb000	0x881aaba000	0x881aabc000	add-on 	/boot/system/add-ons/Translators/WonderBrushTranslator
	4893	0x88488ca000	0x88488d5000	0x8848ad5000	0x8848ad6000	lib    	/boot/system/lib/libiculx.so.57.2
	4886	0x8aec326000	0x8aec38c000	0x8aec58b000	0x8aec590000	lib    	/boot/system/lib/libbnetapi.so
	4873	0x8ba2307000	0x8ba2334000	0x8ba2533000	0x8ba2535000	lib    	/boot/system/apps/Beam/lib/bmDaemon.so
	4887	0x8f94c94000	0x8f94c9b000	0x8f94e9a000	0x8f94e9b000	lib    	/boot/system/lib/libbsd.so
	4937	0x98b534b000	0x98b536d000	0x98b556c000	0x98b556e000	lib    	/boot/system/lib/libIlmImfUtil-2_4.so.24.0.0
	4931	0x9a2adb9000	0x9a2adc8000	0x9a2afc7000	0x9a2afc8000	lib    	/boot/system/lib/libicns.so.1.2.0
	4923	0xa0c6c75000	0xa0c6c87000	0xa0c6e86000	0xa0c6e88000	add-on 	/boot/system/add-ons/Translators/PSDTranslator
	4927	0xac0ed79000	0xac0ed8d000	0xac0ef8d000	0xac0ef8f000	add-on 	/boot/system/add-ons/Translators/JPEG2000Translator
	4885	0xb5d345b000	0xb5d353e000	0xb5d373e000	0xb5d3740000	lib    	/boot/system/lib/libiconv.so.2.6.0
	4896	0xc73edfe000	0xc73ee1a000	0xc73f019000	0xc73f01a000	lib    	/boot/system/lib/libz.so.1.2.11
	4883	0xc752947000	0xc75295d000	0xc752b5c000	0xc752b5d000	lib    	/boot/system/lib/libgcc_s.so.1
	4881	0xcb1476a000	0xcb1477f000	0xcb1497e000	0xcb14980000	lib    	/boot/system/lib/libtranslation.so
	4926	0xd41673c000	0xd416748000	0xd416948000	0xd416949000	add-on 	/boot/system/add-ons/Translators/PCXTranslator
	4944	0xdd6b22b000	0xdd6b238000	0xdd6b438000	0xdd6b439000	add-on 	/boot/system/add-ons/Translators/STXTTranslator
	4939	0xddc5a62000	0xddc5aad000	0xddc5cad000	0xddc5cb1000	lib    	/boot/system/lib/libIex-2_4.so.24.0.0
	4897	0xdfd90db000	0xdfd91a4000	0xdfd93a3000	0xdfd93a4000	lib    	/boot/system/lib/libzstd.so.1.4.4
	4878	0xe1f5235000	0xe1f52ab000	0xe1f54ab000	0xe1f54b6000	lib    	/boot/system/lib/liblayout.so
	4949	0xea3103e000	0xea31239000	0xea31438000	0xea31461000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	4929	0xed8e8e6000	0xed8e8fd000	0xed8eafd000	0xed8eaff000	add-on 	/boot/system/add-ons/Translators/JPEGTranslator
	4948	0xf4d0ea4000	0xf4d0f0b000	0xf4d110a000	0xf4d1115000	lib    	/boot/system/lib/libssl.so.1.0.0
	4911	0xfa18727000	0xfa18758000	0xfa18957000	0xfa18958000	lib    	/boot/system/lib/libpng16.so.16.37.0
	4918	0xfed5f6a000	0xfed5fdc000	0xfed61dc000	0xfed61e0000	lib    	/boot/system/lib/libtiff.so.5.5.0
	4910	0x10376daa000	0x10376dba000	0x10376fb9000	0x10376fbb000	lib    	/boot/system/lib/libbz2.so.1.0.8
	4904	0x1060b19b000	0x1060b1a9000	0x1060b3a9000	0x1060b3aa000	add-on 	/boot/system/add-ons/Translators/PDFTranslator
	4941	0x11037fae000	0x11037fb4000	0x110381b4000	0x110381b5000	lib    	/boot/system/lib/libIlmThread-2_4.so.24.0.0
	4879	0x110b8941000	0x110b8afc000	0x110b8cfb000	0x110b8d16000	lib    	/boot/system/lib/libtracker.so
	4875	0x118824d5000	0x11882516000	0x11882715000	0x1188271e000	lib    	/boot/system/lib/libnetwork.so
	4916	0x1304482e000	0x13044896000	0x13044a95000	0x13044a98000	lib    	/boot/system/lib/libwebp.so.7.1.0
	4907	0x131d86de000	0x131d86f9000	0x131d88f9000	0x131d88fa000	lib    	/boot/system/lib/libjbig2dec.so.0.0.0
	4940	0x13a65661000	0x13a65663000	0x13a65862000	0x13a65863000	lib    	/boot/system/lib/libIexMath-2_4.so.24.0.0
	4871	0x13f289e0000	0x13f289e6000	0x13f28be5000	0x13f28be6000	lib    	/boot/system/apps/Beam/lib/bmRegexx.so
	4902	0x14237ce2000	0x14237cfa000	0x14237ef9000	0x14237efb000	add-on 	/boot/system/apps/Beam/add-ons/Filters/Spam
	4870	0x147f4341000	0x147f435b000	0x147f455b000	0x147f455c000	lib    	/boot/system/apps/Beam/lib/bmBase.so
	4899	0x1568142b000	0x156814b0000	0x156816af000	0x156816bc000	lib    	/boot/system/lib/libssl.so.1.1
	4888	0x15a18002000	0x15a180fd000	0x15a182fc000	0x15a182ff000	lib    	/boot/system/lib/libtextencoding.so
	4868	0x15a504f1000	0x15a50512000	0x15a50711000	0x15a50713000	lib    	/boot/system/runtime_loader
	4909	0x16720e97000	0x16720f09000	0x16721108000	0x1672110a000	lib    	/boot/system/lib/libopenjp2.so.2.3.1
	4884	0x16859212000	0x1685931e000	0x1685951e000	0x16859570000	lib    	/boot/system/lib/libroot.so
	4880	0x16b5753a000	0x16b5769c000	0x16b5789c000	0x16b578b0000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	4869	0x171bf8e7000	0x171bf9eb000	0x171bfbeb000	0x171bfbfb000	app    	/boot/system/apps/Beam/Beam
	4938	0x17cfcb81000	0x17cfcbc3000	0x17cfcdc2000	0x17cfcdc3000	lib    	/boot/system/lib/libHalf-2_4.so.24.0.0
	4892	0x17d9178c000	0x17d917e0000	0x17d919e0000	0x17d919e3000	lib    	/boot/system/lib/libicule.so.57.2
	4915	0x195400a7000	0x195400b5000	0x195402b5000	0x195402b6000	add-on 	/boot/system/add-ons/Translators/WebPTranslator
	4898	0x196740e8000	0x196742f6000	0x196744f6000	0x19674525000	lib    	/boot/system/lib/libcrypto.so.1.1
	4928	0x1a03b68f000	0x1a03b6f8000	0x1a03b8f7000	0x1a03b902000	lib    	/boot/system/lib/libjasper.so.4.0.0
	4932	0x1ac42a40000	0x1ac42a4e000	0x1ac42c4e000	0x1ac42c4f000	add-on 	/boot/system/add-ons/Translators/ICOTranslator
	4908	0x1ac56ab4000	0x1ac56b45000	0x1ac56d45000	0x1ac56d46000	lib    	/boot/system/lib/libjpeg.so.62.3.0
	4903	0x1bc7183c000	0x1bc7186c000	0x1bc71a6b000	0x1bc71a6e000	add-on 	/boot/system/apps/Beam/add-ons/Filters/Sieve
	4891	0x1cf9ea6c000	0x1cf9ea78000	0x1cf9ec77000	0x1cf9ec79000	lib    	/boot/system/lib/libicuio.so.57.2
	4889	0x1d44c1e2000	0x1d44da62000	0x1d44dc61000	0x1d44dc62000	lib    	/boot/system/lib/libicudata.so.57.2
	4936	0x1f362656000	0x1f362824000	0x1f362a24000	0x1f362b29000	lib    	/boot/system/lib/libIlmImf-2_4.so.24.0.0
	4922	0x1f3ed5a4000	0x1f3ed5c0000	0x1f3ed7bf000	0x1f3ed7c2000	add-on 	/boot/system/add-ons/Translators/RAWTranslator
	4882	0x1f53f36a000	0x1f53f67e000	0x1f53f87d000	0x1f53f8ab000	lib    	/boot/system/lib/libbe.so
	4872	0x1f5a4338000	0x1f5a4402000	0x1f5a4601000	0x1f5a4608000	lib    	/boot/system/apps/Beam/lib/bmMailKit.so
	4947	0x20e01bda000	0x20e01be4000	0x20e01de3000	0x20e01de4000	add-on 	/boot/system/apps/Beam/add-ons/NetEndpoints/OpenSslNetEndpoint
```

### PR DESCRIPTION
**Pull request by bmastenbrook**
Fixes #21. Lightly tested and seems to work on my mail server.

### CODE REVIEW

**Comment by waddlesplash** [comment]
A better option, if you have time to implement it, would be to use `BSecureSocket` from the Network Kit instead. But if you don't, I guess we can just merge this.

**Comment by bmastenbrook** [comment]
Is there documentation for `BSecureSocket` somewhere? At first glance, I don't see how to use it for `STARTTLS`, and I don't see how to use client certs with it (which BEAM seems to support).

**Comment by waddlesplash** [comment]
It is indeed not usable for STARTTLS, but I am pretty sure STARTTLS (and insecure IMAP/POP in general) are considered deprecated. Haiku's built in mail client only supports plain TLS now.

There is a callback system you can use to accept or reject certificates that are not in the system store; Web+ uses that to display the SSL errors/questions it does now. Not sure where the code for that GUI, it may just be in Web+.

**Comment by bmastenbrook** [comment]
`STARTTLS` is not insecure, though. It’s just another way to get at TLS, and some mail services only offer SMTP with STARTTLS on port 587.

As for client certificates, allow me to clarify: this is a certificate presented by the mail client to the server as part of authenticating to the server. They supplement password-based authentication by ensuring that only clients in possession of a valid private key and corresponding certificate are allowed to establish a TLS connection to the server. This is a form of two-factor authentication in which the private key and certificate serves as “something you have” and the password is “something you know”. In order to support client certificates, the TLS API needs to provide a mechanism to supply the client certificate (and corresponding private key) when establishing the connection, and I did not see such a mechanism in the header.

Moving to the BSecureSocket class would considerably simplify the code, and perhaps it’s acceptable to remove these features from the client. Unfortunately, I’m not the maintainer (if it has one) or volunteering to maintain it, so I can’t really make that call. I was merely giving it a try, found the package was uninstallable, and came up with the smallest fix for that. If the client works for me, maybe I’ll dive in and clean up other parts, but for now the code would be no worse off with these changes merged.

**Comment by waddlesplash** [comment]
> STARTTLS is not insecure, though. It’s just another way to get at TLS, and some mail services only offer SMTP with STARTTLS on port 587.

Ultimately it is either just inefficient (why not create the TLS connection upfront if you are going to mandate TLS anyway?) or insecure (MITM blocks TLS.) I think there are more mail services without STARTTLS now than there are without plain TLS...

> this is a certificate presented by the mail client to the server as part of authenticating to the server. They ...

Probably this is something that would be good to implement in BSecureSocket, yes.

> Unfortunately, I’m not the maintainer (if it has one)

Yeah, Beam is basically "unmaintained" at this point. Personally I think the built-in Haiku Mail client is worth more investment than Beam is...

**Comment by diversys** [comment]
So, let's just commit this fix then?

**Pull request merged**
