### PR TITLE
Sentence casing all strings

### PR DESCRIPTION
**Pull request by humdingerb**
I looked through Beam compiled with these changes and it all seems fine. It may be a good idea for an actual Beam user to give it a run, to see if everything still works as it should...

### CODE REVIEW

**Comment by humdingerb** [comment]
I force updated the PR, because I wrongly sentence cased the settings files "General Settings" and "Known Addresses"...

I tested a bit more, but I'm not able to send messages. Also, the "From" of new messages is for some reason "humdingerb@gmail.com@gmail.com". I see the same issue with the Beam version installed via HaikuDepot though...

**Comment by diversys** [comment]
Does it happen with 32bit Beam as well?

**Comment by humdingerb** [comment]
I can currently only test on 32bits, as 64bit nightly won't boot properly.

**Comment by humdingerb** [comment]
Also - doesn't seem to work with the Beam version from HaikuDepot either - when trying to send a mail, I see this alert: https://imgur.com/40XCMU9

I'd like to help avoiding the truncated labels etc. but don't know how. If anyone has a hint there...

**Comment by diversys** [comment]
Could you check if ea34050abeb95b1b8de524864f8eab44de396184 (revision before 64bit fixes) is able to send messages?

**Comment by humdingerb** [comment]
False alarm... :}
All versions are able to send emails. I missed expanding the view by clicking the widget next to "Subject" in the "Edit mail" window when creating a new mail and picking an account from the "SMPT-Server" popup menu...
Strange that Beam doesn't default to the single account I've created (Gmail). Or did I miss some preference?

**Comment by humdingerb** [comment]
Aha!
I was unfamiliar with the "Identities" concept of Beam. Filling out one of those fixes my "humdingerb@gmail.com@gmail.com" From-field and having to set the SMPT_Server for every new mail.
All is good. :)

**Pull request merged**
